
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 14 12:06:30 BRST 2004
//----------------------------------------------------

package SATS;

/** CUP generated class containing symbol constants. */
public class SATSsym {
  /* terminals */
  public static final int AND = 3;
  public static final int SIGN = 10;
  public static final int EOL = 8;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IMPLIES = 5;
  public static final int RPAREN = 7;
  public static final int NEG = 2;
  public static final int LPAREN = 6;
  public static final int OR = 4;
}

