
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 14 12:27:31 BRST 2004
//----------------------------------------------------

package ConversorWagnerSATLIB;

/** CUP generated class containing symbol constants. */
public class ConversorWagnerSATLIBsym {
  /* terminals */
  public static final int AND = 5;
  public static final int SIGN = 2;
  public static final int EOL = 3;
  public static final int TRUE = 11;
  public static final int EOF = 0;
  public static final int FALSE = 12;
  public static final int ID = 13;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int IMPLIES = 7;
  public static final int NEG = 4;
  public static final int LPAREN = 9;
  public static final int OR = 6;
  public static final int BIIMPLIES = 8;
}

