
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 15 14:10:10 BRST 2004
//----------------------------------------------------

package satcnf2;

/** CUP generated class containing symbol constants. */
public class satcnf2sym {
  /* terminals */
  public static final int ENDOFCLAUSE = 3;
  public static final int error = 1;
  public static final int CLAUSES = 6;
  public static final int NUMBER = 7;
  public static final int NEG = 2;
  public static final int VARIABLES = 5;
  public static final int FINAL = 4;
  public static final int EOF = 0;
}

