
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 14 12:07:21 BRST 2004
//----------------------------------------------------

package sats3;

/** CUP generated class containing symbol constants. */
public class sats3sym {
  /* terminals */
  public static final int AND = 3;
  public static final int SIGN = 12;
  public static final int EOL = 8;
  public static final int TOP = 9;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int BOTTOM = 10;
  public static final int IMPLIES = 5;
  public static final int RPAREN = 7;
  public static final int NEG = 2;
  public static final int LPAREN = 6;
  public static final int OR = 4;
}

